### ISSUE TITLE
AgeInfo.xml not found

### ISSUE THREAD

**Issue by Jimjipeng** [antoinesauray/GenderAgeClassifier#1]
where do download and extract AgeInfo.xml？

**Comment by asauray** [comment]
The file is too big to be incorporated in the Git repository. I will provide a Google Drive url and include it in a Readme file. 
[https://drive.google.com/file/d/0B3FCJcdqdKiAckdnLVFiWGpCZk0/view?usp=sharing](AgeInfo.xml)
